### PR TITLE
Modularization in Java-11

### PR DESCRIPTION
**Pull request by dan323**
Add modules to work with java 11

### CODE REVIEW

**Comment by fathzer** [comment]
Hello Daniel,

Thank you very much for your pull request. I had a quick look at it.

My first remark is that the library must be able to be used with Java 8; Java 8 is [still supported by Oracle](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) and is, in particular, still used extensively by the company that employs me. So targetting this library for Java 11 is excluded.

Being totally incompetent in Jigsaw, I have not managed to make a java 8 compliant version with modules. I will try to have a closer look at it this weekend.

Best regards,
Jean-Marc

**Comment by dan323** [comment]
Hello Jean-Marc,

the simplest solution is to maintain 2 major versions of your library. There is another option that Oracle developed for such cases, but is more complicated. I can take a look at this second possibility when I have more time.

Consider that Oracle has extended support for Java 8 until 2030, but for a fee. It is not free as the current LTS versions.

Thank you,
Daniel de la Concepción

**Comment by fathzer** [comment]
Hi again
> the simplest solution is to maintain 2 major versions of your library. There is another option that Oracle developed for such cases, but is more complicated. I can take a look at this second possibility when I have more time.

I've found [this](https://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html) that seems to explain how to make a unique jar compatible with java 8, and containing module definitions. This second option has clearly my preference and seems to be the one adopted by major libraries like junit or jackson.

I can't currently try, but I could ... tomorrow.

> Consider that Oracle has extended support for Java 8 until 2030, but for a fee. It is not free as the current LTS versions.

Yes, I have seen it. But believe me, my colleagues would simply stop updating the library instead of migrating some huge applications they maintain to Java 11, or 21 (and might post an enhancement request to add Java 8 support ;-)). They prefer a massive migration to Java, say ... 45, in 2029 ... maybe because it probably won't be their responsibility ;-)

**Comment by dan323** [comment]
I added a new commit to allow multirelease.

**Comment by fathzer** [comment]
Hello Daniel,

I was able to create a Java 8 compatible jar with module declarations thanks to the info I was talking about yesterday :-)
I still have to update the syntax of my code to Java 8 style (typically remove class names in constructors like new ArrayList<String> - see https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&issueStatuses=OPEN%2CCONFIRMED&branch=release-3.0.5&id=fathzer_javaluator).
I also have a small deployment problem on Maven central, which has just banned the use of user/pwd in favor of tokens.
All this should be able to be done quickly ... but not today ;-)

Best regards,
Jean-Marc

PS: Everything is in 'release-3.0.5' branch.

**Comment by dan323** [comment]
It is similar to what I did in this PR, but excluding instead of adding the new folder.

**Comment by fathzer** [comment]
Hello Daniel,

> It is similar to what I did in this PR, but excluding instead of adding the new folder.

Yes it is clearly the same idea. And it's also clear that without your help I would never been able to solve the "module problem".

But, in your PR, mvn produces multi-release jars, in my branch it makes "classical" jars. Maybe it is the reason why, when I tried 'javap javaluator-3.0.4.jar --describe-modules' with java 21 on the jar built with your PR, it returned no modules:
```
releases: 11

No root module descriptor, specify --release
```
With the "classical" jar (which is also the solution adopted by junit and jackson), I get:
```
javaluator@3.0.5 jar:file:///C:/Users/jeanm/git/javaluator/javaluator/target/javaluator-3.0.5.jar!/module-info.class
exports com.fathzer.soft.javaluator
requires java.base mandated
``` 
Best Regards

**Comment by dan323** [comment]
I will wait for the new version to be released. 🙇‍♂️

**Comment by fathzer** [comment]
Hello Daniel,

I just released version 3.0.5. Please tell me if it fixes the problems encountered with previous versions.

Best regards,
Jean-Marc

**Pull request closed without merging**
